### ISSUE TITLE
Incorrect object zsd_customer_util used in class zcl_cmd_vat

### ISSUE THREAD

**Issue by gjaspalibm** [fidley/Customers#2]
Hi,

Thanks for sharing this. just a minor correction on below code for class zcl_cmd_vat.

Line 48  insert value #( task = zsd_customer_util=>mode-create

Line 65  <vat>-task = zsd_customer_util=>mode-change.

Line 80 <vat>-task = zsd_customer_util=>mode-delete.

Instead of zsd_customer_util it has to be zcl_cmd_util

Regards
Gurpreet

**Comment by fidley** [comment]
Thanks @gjaspalibm for info. This is solved now.
