### ISSUE TITLE
customer number convert alpha in Class ZCL_CMD_CUSTOMER->CONSTRUCTOR

### ISSUE THREAD

**Issue by vidyadharg** [fidley/Customers#4]
I like you solution, thankyou very much for sharing. another suggestion.

customer number convert alpha in Class ZCL_CMD_CUSTOMER->CONSTRUCTOR

Class ZCL_CMD_CUSTOMER->CONSTRUCTOR
  method constructor.
*    customer = i_customer.
          CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
            EXPORTING
              input  = i_customer
            IMPORTING
              output = customer.

**Comment by fidley** [comment]
Very good one. I'll add it when I will finally touch it again. Hopefully very soon.
