### ISSUE TITLE
Changes not reflecting in BP but KNA1 and ADRC is getting updated

### ISSUE THREAD

**Issue by rajeshrajgor** [fidley/Customers#5]
Hi Fidley,
First of all, this library is wonderful. 
I tried to update POSTAL-CODE1 and CITY1 and it is successfully got updated in KNA1 but when I run BP with specified KUNNR, it shows me an old value. I debugged BP and I found that it is going to get values from BUT020 table with different ADRNR.

**Comment by fidley** [comment]
Hello @rajeshrajgor, 

so far I haven't worked with BP, maybe they need other approach. I saw somewhere that there is one additional class that contains both vendors and customers and it is tailored for the BP I guess. I will try to find it.

**Comment by rajeshrajgor** [comment]
Hello @fidley 
Thanks for your reply. For now, I have used BDC recording to create customer/vendor. I also continue looking into this and will update here if I get any solution.
